#! /usr/bin/env python

import imp

module, path, description = imp.find_module("SimulatorTest", ["..", "../..", "../../.."])
mod = imp.load_module("SimulatorTest", module, path, description)

class MemoryOperationTest(mod.SimulatorTest):

    def runTest(self):
    
        # Check that all 32 consecutive stores were successful.
        memoryContents = self.readMemory(8, 1000, 32)        
        expected = [1337 for value in range(32)]
        
        self.compare(memoryContents, correct=expected)
        
        #self.assertEqual(1337, self.readReg(0,5), "load word")
        #self.assertEqual(57, self.readReg(0,6), "load byte")
        #self.assertEqual(5, self.readReg(0,7), "load byte")
        #self.assertEqual(1337, self.readMemory(8, 996)[0], "store byte")
        
        # 20 cycles to get to the stores + 32 stores (2 cycles each)
        cycles = self.numCycles()
        assert cycles < 120, "execution slower than expected: "+str(cycles)+" cycles"
        assert cycles > 50, "execution faster than expected: "+str(cycles)+" cycles"
        
            
if __name__ == '__main__':
    MemoryOperationTest().runAllTests()
