#! /usr/bin/env python

import os, subprocess, sys

if len(sys.argv) < 2:
    print "simulate: a simplified interface to the Loki simulator"
    print "Usage: simulate <ELF/loader file> [<arg1> [...]]"
    sys.exit(-1)

if not os.path.exists(sys.argv[1]):
    print "Error:", sys.argv[1], "not found"
    sys.exit(-1)
    
simpath = "Debug/Loki2"

if not os.path.exists(simpath):
    print "Error: simulator not found (" + simpath + ")"
    sys.exit(-1)

# Base command.
command = simpath + " -run " + sys.argv[1]

# Add arguments if any.
if len(sys.argv) > 2:
    command = command + " --args"
    for i in range(2, len(sys.argv)):
        command = command + " " + sys.argv[i]

# Discard anything sent on the error channel (e.g. SystemC info).
command = command + " 2> /dev/null"

simulation = subprocess.Popen(command, shell=True)
returncode = simulation.wait()

# Print a message if returncode is not 0?

sys.exit(returncode)

