#! /usr/bin/env python

import imp

module, path, description = imp.find_module("TransposeTest", ["..", "test_files/transpose"])
mod = imp.load_module("TransposeTest", module, path, description)

class TransposeSIMDTest(mod.TransposeTest):

    def runAllTests(self):
        # May want to change number of SIMD members and test several times.
        # TODO: check command line options for this.
        self.simdTest(8,8)
    
if __name__ == '__main__':
    TransposeSIMDTest().runAllTests()
