#! /usr/bin/env python

import imp

module, path, description = imp.find_module("MatMultTest", [".."])
mod = imp.load_module("MatMultTest", module, path, description)

class MatMult1CoreTest(mod.MatMultTest):
    pass     
    
if __name__ == '__main__':
    MatMult1CoreTest().runAllTests()
