#! /usr/bin/env python

import imp

module, path, description = imp.find_module("RGB2YUVTest", ["..", "test_files/rgb2yuv"])
mod = imp.load_module("RGB2YUVTest", module, path, description)

class RGB2YUV1CoreTest(mod.RGB2YUVTest):
    pass     
    
if __name__ == '__main__':
    RGB2YUV1CoreTest().runAllTests()
