#! /usr/bin/env python

import imp

module, path, description = imp.find_module("FIRTest", ["..", "test_files/fir"])
mod = imp.load_module("FIRTest", module, path, description)

class FIR1CoreTest(mod.FIRTest):
    # Everything is defined in superclasses.
    pass
            
if __name__ == '__main__':
    FIR1CoreTest().runAllTests()
