#! /bin/bash

if [ $# -ne 1 ];
then
    echo "simdfy: Tool for linking an object file with the SIMD startup phase."
    echo "Usage: simdfy file"
    exit
fi

#Find the SIMD object file (it should be in the same directory as the script).
simdfile="`dirname $0`/simd"

infile=$1
simd="_simd"
outfile=$infile$simd

if [ -e $infile ];
then
    if [ -e $simdfile ];
    then
        # TODO: don't hard-code the library location
        loki-elf-ld -o $outfile $simdfile $infile -L/local/scratch/db434/workspace/lokiprefix/loki-elf/lib -Tsim.ld
    else
        echo "Could not find $simdfile"
        exit
    fi
else
    echo "Could not find $infile"
    exit
fi