#! /usr/bin/env python

import imp

module, path, description = imp.find_module("ZigzagTest", ["..", "test_files/zigzag"])
mod = imp.load_module("ZigzagTest", module, path, description)

class ZigzagLatencyTest(mod.ZigzagTest):
    # Everything is defined in superclasses.
    pass
            
if __name__ == '__main__':
    ZigzagLatencyTest().runAllTests()
