#! /usr/bin/env python

import imp

module, path, description = imp.find_module("SimulatorTest", ["..", "../..", "../../.."])
mod = imp.load_module("SimulatorTest", module, path, description)

class DCTTest(mod.SimulatorTest):

    def runTest(self):
        # Read 64 values from memory 15.
        result = self.readMemory(15, 0, 64)
        
        # See if the memory contents match the contents of the file.
        self.compare(result, filename=".expected")
            
if __name__ == '__main__':
    DCTTest().runAllTests()
