#! /usr/bin/env python

import imp

module, path, description = imp.find_module("FIRTest", [".."])
mod = imp.load_module("FIRTest", module, path, description)

class FIRSIMDTest(mod.FIRTest):
    
    def runAllTests(self):
        # May want to change number of SIMD members and test several times.
        # TODO: check command line options for this.
        simdMembers = self.fileContents("params.data")[0]
        self.test(description = str(simdMembers) + " cores")
            
if __name__ == '__main__':
    FIRSIMDTest().runAllTests()
