#! /usr/bin/env python

import imp

module, path, description = imp.find_module("SimulatorTest", ["test_files", "../.."])
mod = imp.load_module("SimulatorTest", module, path, description)

class nxipkTest(mod.SimulatorTest):
    
    def runTest(self):
        pass
        
            
if __name__ == '__main__':
    nxipkTest().runAllTests()
    