#! /usr/bin/env python

import imp

module, path, description = imp.find_module("RGB2YUVTest", ["..", "test_files/rgb2yuv"])
mod = imp.load_module("RGB2YUVTest", module, path, description)

class RGB2YUVSIMDTest(mod.RGB2YUVTest):

   def runAllTests(self):
        # May want to change number of SIMD members and test several times.
        # TODO: check command line options for this.
        self.simdTest(8,8)
    
if __name__ == '__main__':
    RGB2YUVSIMDTest().runAllTests()
