name: C/C++ CI

on:
  push:
    branches: [ master, accelerator ]
  pull_request:
    branches: [ master, accelerator ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: cd build && make -j8
