#! /usr/bin/env python

import imp

module, path, description = imp.find_module("RGB2YUVTest", ["..", "test_files/rgb2yuv"])
mod = imp.load_module("RGB2YUVTest", module, path, description)

class RGB2YUVDataflowTest(mod.RGB2YUVTest):
    
    # Collect result from simulator (need to access different memories now
    # that more cores are being used)
    def getResult(self):
        y = self.toBytes(self.readMemory(16, 0x20000, self.length))
        u = self.toBytes(self.readMemory(16, 0x21000, self.length))
        v = self.toBytes(self.readMemory(24, 0x22000, self.length))
        return zip(y,u,v)
    
if __name__ == '__main__':
    RGB2YUVDataflowTest().runAllTests()
